### ISSUE TITLE
Does this cache the store locations?

### ISSUE THREAD

**Issue by Quentin100** [jdaehne/GoogleStoreLocator#15]
I use this on a website with around 50 stores. I offer a proximity search to find the nearest stores within a 30 mile radius. However, in the last two months, my geocoding calls with Google Maps have jumped nearly 8x from 50k a month to over 400k a month. I know for sure that I am not having 400k location search a month on this website, so I am wondering if calling the snippet uncached means I am looking up all 50 odd store locations on every search?

**Comment by jdaehne** [comment]
Hi @Quentin100 ,

if you are using version 2.x all the stores are cached. There is only a new request to the api when you edit the store. Otherwise all the lat/lng data comes from the cache for the sore.

The only thing that does a request to the Google-Api is when the user inputs a address to search for. Then you have 1 request for the users address. 

The other request is placed by setting a location to filter the stores. This location also does a request to the api on every load of the site. Does that may cause the amount of requests?
Actually that request could also be cached to avoid unnecessary requests. I think i allready have that on the to-do list...

**Comment by Quentin100** [comment]
Hi @jdaehne,

I am using version 2.0.3, so the Store Locations should be cached. Also I only have the &locations set on the landing page, so it shouldn't increment the traffic by that much.  I think it is an issue with the API Key rather that the Extra. Will carry on the fight with Google. Please feel free to close this issue as I didn't know how else to reach out to you to ask.

Thanks,

Quentin

**Comment by Quentin100** [comment]
@jdaehne Thanks for the support.
