### ISSUE TITLE
Small bugs

### ISSUE THREAD

**Issue by berj** [jdaehne/GoogleStoreLocator#4]
OSX : 10.11.4
MAMPro : 3.5
Safari  9.1
Google 49
Firefox 45
Modx 2.4.3

I just install GoogleStoreLocator and I have two small bugs with it:

**1)** myPosition button
Under Safari when I click on «myPosition» nothing append. 
Under Chrome and Firefox when I click on  «myPosition» it return me to the home page with this url : http://colline:8888/index.php?id=97?lat=49.404179299999996&lng=-71.7575181.

Is it because I am in a local environment?

**2)** if I use a name for a store with an apostrophe  like «L'Épicerie futée» the map is not display and got these two error message in Safari web console:  
a) SyntaxError: Unexpected identifier 'Épicerie'. Expected '}' to end a object literal.
b) InvalidValueError: initMap is not a function

Thank very much for this Extra

**Comment by jdaehne** [comment]
Hi berj,

thanks a lot for this report.

**1)** This seems a Safari-Bug. Safari has problems to get geodata when the computer is not connected via wifi. It seems that is only working with wifi on. So i think there is nothing i can do about.

**2)** I fixed that. The single quote in "L'Épicerie futée" breaks the JS-String. Now all the placeholder for the map-marker get escaped. So that should work now.

Thanks for the report and beste regards...

Jan
